# Generated by Django 3.2.16 on 2023-02-13 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='image',
        ),
        migrations.AlterField(
            model_name='menu',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='menu',
            name='item',
            field=models.CharField(choices=[('Starter', 'starter'), ('Main', 'main'), ('Dessert', 'dessert')], max_length=20),
        ),
    ]
