# Generated by Django 3.2.16 on 2023-03-03 11:21

from django.db import migrations, models
import reservation.models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20230223_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateField(blank=True, default=None, null=True, validators=[reservation.models.Reservation.validate_date]),
        ),
    ]
